services:
  app:
    image: python:3.11-slim
    working_dir: /app
    volumes:
      - ./:/app
    command: bash -lc "pip install -r requirements.txt && tail -f /dev/null"
    tty: true
    stdin_open: false

